### ISSUE TITLE
Drag top of app to move window around

### ISSUE THREAD

**Issue by pedromvpg** [KayBeSee/lily-wallet#12]
On MacOS, I can't use the top of the window to move it around on my desktop.

<img width="1642" alt="Screen Shot 2020-08-17 at 11 56 11 AM" src="https://user-images.githubusercontent.com/807505/90416785-eb84b500-e080-11ea-8aba-08d5349671ad.png">

**Comment by KayBeSee** [comment]
This is fixed in the next update
