### ISSUE TITLE
Transaction details wrong (outputs greater then inputs)

### ISSUE THREAD

**Issue by djpnewton** [KayBeSee/lily-wallet#21]
Testing with a testnet wallet and in some cases the transaction details preview is wrong. The transaction is valid when broadcast.. there must be a difference in outputs sent to this preview screen and those used in creating the transaction

![Screen Shot 2020-08-31 at 9 09 13 PM](https://user-images.githubusercontent.com/42459/91703893-04d44800-ebcf-11ea-9e10-e7a55fdc28d5.png)

**Comment by KayBeSee** [comment]
What is the transaction history look like for this wallet?

It's weird that Input #0 and Output #0 are the same. Are you reusing addresses?

**Comment by djpnewton** [comment]
here are the txids:
c3822a07ef3322767ff715f0aa20a1c42173038c2bb8dee54a0f207945b1fca7
822f9c2a5de3da2f9f4d0f25df08a5d4d5a5fccec963394d62e0d151723ad636
18d3c349f27d22816f0d34dd17d07e6c26c31676c11aa2fb9be14fc629efc779
a6278525266af4919d6b45aa383b0c329572be121439842abb3436a135c979b8

its just using a testnet faucet and then moving some funds internally (yes reusing an address in that example)

**Comment by KayBeSee** [comment]
I just merged a fix, can you verify that it fixed the issue?

**Comment by djpnewton** [comment]
yes that did it
