### ISSUE TITLE
Home component sits above MobileNavbar in z-order

### ISSUE THREAD

**Issue by djpnewton** [KayBeSee/lily-wallet#26]
This means you cannot see the mobile navbar menu items.

It seems to be caused by the spring animation: https://github.com/KayBeSee/lily-wallet/blob/1bf910019e4942ccb194583f6f8413b682cbb6b8/src/pages/Home.js#L75

![Screen Shot 2020-09-02 at 6 21 32 PM](https://user-images.githubusercontent.com/42459/91939231-923ba780-ed49-11ea-9dcf-3b2ab2d58ac7.png)

**Comment by KayBeSee** [comment]
This should go away with the latest release in the `next` branch. Completely new mobile navigation.
