### ISSUE TITLE
Balance graph keeps growing if you send money to yourself 

### ISSUE THREAD

**Issue by bilthon** [KayBeSee/lily-wallet#39]
This happens because transactions are classified as `sent` or `received` only. But there's a third possibility in which the user might be sending funds to himself. This happens a lot when testing, but it could also be the case when a real user decides to consolidate his/her UTXOs to take advantage of a low fee environment for example.

I propose we classify these transactions with the `moved` label and take special care of this situation.

See this [screenshot](https://imgur.com/a/FOlX1mn) as an example. That particular wallet was only funded with 10 mBTC, and the subsequent transactions were only self-transfers. The balance graph should be slowly decaying, considering the only decrement of balance was caused by miner fees. But instead it just grows.

I hope to provide a PR solving this issue in the coming days, but any feedback is welcome.

**Comment by KayBeSee** [comment]
Fixed in #40
