### ISSUE TITLE
Can't create wallet from one hardware wallet device

### ISSUE THREAD

**Issue by HardCorePawn** [KayBeSee/lily-wallet#7]
Tried to create a wallet using a single hardware wallet.

- Creating a normal "wallet" just gives 24 word seed and no option to connect HW.
- Creating a "vault", after 1 device is connected, there is no "create wallet" option, I can only add more HW devices

Tried with both Trezor ONE and Ledger Nano S. Ledger Nano S is detected and connected OK, but unable to create wallet, Trezor ONE is not even able to be connected ([as per other issue](https://github.com/KayBeSee/lily-wallet/issues/6))

Is it not possible to just use a single hardware wallet at this time?

**Comment by KayBeSee** [comment]
Single hardware wallets aren't supported at the moment. It's high on the roadmap though.

**Comment by KayBeSee** [comment]
Support for single hardware wallets was added. Closing this.
